import assert from "node:assert/strict";
import { Readable } from "node:stream";
import { test } from "node:test";
import type { IncomingMessage, ServerResponse } from "node:http";
import { createOrganizationProfile, handleOrganizationProfile } from "../src/organization-profile.js";
import { organizationProfilePrincipalRef, organizationProfileRecordRef } from "@studenthub/organizations";
import type { CommitInput, Receipt, SafeWriteStore } from "@studenthub/safe-write-contract";
const ORIGIN="https://studenthub.example.invalid",SESSION="a".repeat(43),PERSON="owner",ORG="org-a",SECRET="shu300-test-secret-is-at-least-thirty-two-bytes";
let value:string|null=null,receipt:Receipt|null=null;
const store={forPrincipal():SafeWriteStore{return {ownedRecord:(p)=>p===organizationProfilePrincipalRef(PERSON)?organizationProfileRecordRef(ORG):null,readField:()=>value,commit:(i:CommitInput)=>{if(value!==i.expectedBefore)return {ok:false,reason:"state_changed"};value=i.value;receipt=i.receipt;return {ok:true};}}},readReceipt:async()=>receipt};
const sessions={get:async(id:string)=>id===SESSION?{id:SESSION,personId:PERSON}:undefined};
async function call(service:ReturnType<typeof createOrganizationProfile>,path:string,body:unknown){const req=Readable.from([JSON.stringify(body)]) as IncomingMessage;req.url=path;req.method="POST";req.headers={origin:ORIGIN,"content-type":"application/json",cookie:`__Host-studenthub_session=${SESSION}`};let status=0,payload="";let headers:Record<string,string>={};const fake={headersSent:false,writeHead(code:number,next:Record<string,string>){status=code;headers=next;fake.headersSent=true;return fake;},end(chunk?:string){payload=chunk??"";return fake;},destroy(){return fake;}};const res=fake as unknown as ServerResponse;assert.equal(await handleOrganizationProfile(req,res,service,ORIGIN),true);return {status,headers,body:JSON.parse(payload) as Record<string,unknown>};}
test("SHU-300 HTTP real handler previews and confirms with hardened headers",async()=>{value=null;receipt=null;const service=createOrganizationProfile({sessions,store,secret:SECRET});const change={orgId:ORG,field:"website",value:"https://example.invalid"};const p=await call(service,"/organization/profile/preview",change);assert.equal(p.status,200);assert.equal(p.headers["x-content-type-options"],"nosniff");assert.equal(p.headers["referrer-policy"],"no-referrer");const done=await call(service,"/organization/profile/confirm",{...change,token:p.body.token});assert.equal(done.status,200);assert.equal(value,change.value);});
test("SHU-300 HTTP hides a non-owner as not found",async()=>{const hidden=createOrganizationProfile({sessions,store:{...store,forPrincipal:()=>({ownedRecord:()=>null,readField:()=>null,commit:()=>({ok:false,reason:"not_own_record"})})},secret:SECRET});const r=await call(hidden,"/organization/profile/preview",{orgId:ORG,field:"name_en",value:"Acme"});assert.deepEqual([r.status,r.body],[404,{error:"not_own_record"}]);});
test("SHU-300 HTTP rejects a malformed receipt path as invalid",async()=>{const service=createOrganizationProfile({sessions,store,secret:SECRET});const req=Readable.from([]) as IncomingMessage;req.url=`/organization/profile/%E0%A4%A/receipts/${"a".repeat(64)}`;req.method="GET";req.headers={cookie:`__Host-studenthub_session=${SESSION}`};let status=0,payload="";const fake={headersSent:false,writeHead(code:number){status=code;fake.headersSent=true;return fake;},end(chunk?:string){payload=chunk??"";return fake;},destroy(){return fake;}};assert.equal(await handleOrganizationProfile(req,fake as unknown as ServerResponse,service,ORIGIN),true);assert.deepEqual([status,JSON.parse(payload)],[400,{error:"invalid_request"}]);});
