import type {IncomingMessage,ServerResponse} from "node:http";
import type {SessionStore} from "@studenthub/login-contract";
import {createOrganizationProfileWrites,type OrganizationProfileStore,type ProfileWriteResult} from "@studenthub/organizations";
import type {SafeWriteSecret} from "@studenthub/safe-write-contract";
export interface OrganizationProfileService {preview(session:string|undefined,org:string,body:unknown):Promise<ProfileWriteResult>;confirm(session:string|undefined,org:string,body:unknown):Promise<ProfileWriteResult>;receipt(session:string|undefined,org:string,ref:string):Promise<ProfileWriteResult>}
export function createOrganizationProfileService(p:{sessions:Pick<SessionStore,"get">;store:OrganizationProfileStore;secret:SafeWriteSecret}):OrganizationProfileService{const writes=createOrganizationProfileWrites(p);const run=async(s:string|undefined,fn:(id:string)=>Promise<ProfileWriteResult>)=>{const x=s?await p.sessions.get(s):undefined;return x?fn(x.personId):{status:404 as const,body:{error:"not_found"}}};return {preview:(s,o,b)=>run(s,id=>writes.preview(id,o,b)),confirm:(s,o,b)=>run(s,id=>writes.confirm(id,o,b)),receipt:(s,o,r)=>run(s,id=>writes.receipt(id,o,r))};}
const route=/^\/organizations\/([^/]+)\/profile\/(preview|confirm|receipts\/([0-9a-f]{64}))$/;
const cookie=(h:string|undefined)=>h?.split(";").map(x=>x.trim().split("=")).find(x=>x[0]==="__Host-studenthub_session")?.[1];
async function json(r:IncomingMessage){const a:Buffer[]=[];let n=0;for await(const x of r){const b=Buffer.from(x);n+=b.length;if(n>8192)return undefined;a.push(b)}try{return JSON.parse(Buffer.concat(a).toString()) as unknown}catch{return undefined}}
export async function handleOrganizationProfile(r:IncomingMessage,s:ServerResponse,service:OrganizationProfileService|undefined,origin:string|undefined){const m=route.exec(new URL(r.url??"/","http://invalid").pathname);if(!m)return false;const send=(x:ProfileWriteResult)=>{s.writeHead(x.status,{"content-type":"application/json","cache-control":"no-store","referrer-policy":"no-referrer"});s.end(JSON.stringify(x.body))};if(!service||!origin){send({status:503,body:{error:"unavailable"}});return true}if(m[3]){if(r.method!=="GET"){send({status:404,body:{error:"not_found"}});return true}send(await service.receipt(cookie(r.headers.cookie),decodeURIComponent(m[1]!),m[3]));return true}if(r.method!=="POST"||r.headers.origin!==origin||r.headers["content-type"]!=="application/json"){r.resume();send({status:404,body:{error:"not_found"}});return true}const body=await json(r);if(body===undefined){send({status:400,body:{error:"invalid_request"}});return true}send(await (m[2]==="preview"?service.preview(cookie(r.headers.cookie),decodeURIComponent(m[1]!),body):service.confirm(cookie(r.headers.cookie),decodeURIComponent(m[1]!),body)));return true}
