import type {IncomingMessage,ServerResponse} from "node:http";
import type {AuthzStore} from "@studenthub/contracts";import type {SessionStore} from "@studenthub/login-contract";
import {PostgresAuthzStore,PostgresLoginStore} from "@studenthub/db";
import {FileDocumentStore,PrivateDocuments,type DocumentStore,DocumentError} from "../../../packages/private-documents/src/index.js";
import {organizationDocumentInput} from "../../../packages/private-documents/src/organization-documents.js";
export function createOrganizationDocuments(p:{store:DocumentStore;authz:AuthzStore;sessions:SessionStore;origin:string;signingKey:Uint8Array;now?:()=>number}){return new PrivateDocuments({...p,authenticate:async credential=>{const s=await p.sessions.get(credential);return s?{kind:"principal" as const,principalId:s.personId}:null}})}
const route=/^\/organizations\/([^/]+)\/documents\/(company-logo|commercial-licence)(?:\/([0-9a-f-]{36})(?:\/(delivery))?)?$/;
function session(h:string|undefined){for(const i of h?.split(";")??[]){const[k,...v]=i.trim().split("="),x=v.join("=");if(k==="__Host-studenthub_session"&&/^[A-Za-z0-9_-]{43}$/.test(x))return x}return""}
export async function handleOrganizationDocuments(r:IncomingMessage,s:ServerResponse,service:PrivateDocuments|undefined){if(r.url?.startsWith("/private-documents/delivery?")){if(!service){s.writeHead(503);s.end();return true}await service.handleDelivery(r,s);return true}const m=route.exec(new URL(r.url??"/","http://invalid").pathname);if(!m)return false;const send=(status:number,body:unknown)=>{s.writeHead(status,{"content-type":"application/json","cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer"});s.end(JSON.stringify(body))};if(!service){send(503,{error:"unavailable"});return true}try{const credential=session(r.headers.cookie),org=decodeURIComponent(m[1]!),type=m[2]!,id=m[3];if(m[4]){if(r.method!=="POST"||!id)throw new DocumentError("invalid");send(200,await service.issueDelivery(credential,id));return true}if(r.method==="DELETE"&&id){await service.remove(credential,id);send(200,{removed:true});return true}if(r.method!=="POST"){send(404,{error:"not_found"});return true}const chunks:Buffer[]=[];for await(const c of r)chunks.push(Buffer.from(c));const body=JSON.parse(Buffer.concat(chunks).toString("utf8")) as {mime?:unknown;bytes?:unknown};if(typeof body.mime!=="string"||typeof body.bytes!=="string")throw new DocumentError("invalid");const bytes=Buffer.from(body.bytes,"base64");if(bytes.toString("base64")!==body.bytes)throw new DocumentError("invalid");const input=organizationDocumentInput(org,type,body.mime,bytes);send(200,id?await service.replace(credential,id,input):await service.upload(credential,input))}catch(e){const code=e instanceof DocumentError?e.code:"unavailable";send(code==="unavailable"?503:code==="invalid"?400:404,{error:code==="denied"?"not_found":code})}return true}
export async function createRuntimeOrganizationDocumentsFromEnv(env:NodeJS.ProcessEnv=process.env){const names=["ORGANIZATION_DOCUMENT_ROOT","ORGANIZATION_DOCUMENT_ORIGIN","ORGANIZATION_DOCUMENT_SIGNING_KEY"] as const;if(names.every(n=>env[n]===undefined))return undefined;if(names.some(n=>!env[n])||!env.DATABASE_URL)throw new Error("invalid organization-document configuration");const key=Buffer.from(env.ORGANIZATION_DOCUMENT_SIGNING_KEY!,"base64");if(key.toString("base64")!==env.ORGANIZATION_DOCUMENT_SIGNING_KEY||key.length<32)throw new Error("invalid organization-document configuration");const store=await FileDocumentStore.open(env.ORGANIZATION_DOCUMENT_ROOT!),authz=new PostgresAuthzStore({connectionString:env.DATABASE_URL}),login=new PostgresLoginStore({connectionString:env.DATABASE_URL});return{service:createOrganizationDocuments({store,authz,sessions:login.sessions,origin:env.ORGANIZATION_DOCUMENT_ORIGIN!,signingKey:key}),close:async()=>Promise.all([authz.close(),login.close()]).then(()=>undefined)}}
