import type {IncomingMessage,ServerResponse} from "node:http";
import type {SessionStore} from "@studenthub/login-contract";
import {createOrganizationProfileWrites,type OrganizationProfileStore,type ProfileWriteResult} from "@studenthub/organizations";
import type {SafeWriteSecret} from "@studenthub/safe-write-contract";
export interface OrganizationProfileService{preview(session:string|undefined,org:string,body:unknown):Promise<ProfileWriteResult>;confirm(session:string|undefined,org:string,body:unknown):Promise<ProfileWriteResult>;receipt(session:string|undefined,org:string,ref:string):Promise<ProfileWriteResult>}
export function createOrganizationProfileService(p:{sessions:Pick<SessionStore,"get">;store:OrganizationProfileStore;secret:SafeWriteSecret}):OrganizationProfileService{const writes=createOrganizationProfileWrites(p);const run=async(s:string|undefined,fn:(id:string)=>Promise<ProfileWriteResult>)=>{const x=s?await p.sessions.get(s):undefined;return x?fn(x.personId):{status:404 as const,body:{error:"not_found"}}};return{preview:(s,o,b)=>run(s,id=>writes.preview(id,o,b)),confirm:(s,o,b)=>run(s,id=>writes.confirm(id,o,b)),receipt:(s,o,r)=>run(s,id=>writes.receipt(id,o,r))}}
const route=/^\/organizations\/([^/]+)\/profile\/(preview|confirm|receipts\/([0-9a-f]{64}))$/,LIMIT=8192;
function cookie(h:string|undefined){for(const item of h?.split(";")??[]){const[key,...rest]=item.trim().split("="),value=rest.join("=");if(key==="__Host-studenthub_session"&&/^[A-Za-z0-9_-]{43}$/.test(value))return value}return undefined}
async function json(r:IncomingMessage):Promise<{ok:true;value:unknown}|{ok:false}>{if(Number(r.headers["content-length"])>LIMIT){r.resume();return{ok:false}}const a:Buffer[]=[];let n=0;for await(const x of r.iterator({destroyOnReturn:false})){const b=Buffer.from(x);n+=b.length;if(n>LIMIT){r.resume();return{ok:false}}a.push(b)}try{return{ok:true,value:JSON.parse(Buffer.concat(a).toString("utf8")) as unknown}}catch{return{ok:false}}}
export async function handleOrganizationProfile(r:IncomingMessage,s:ServerResponse,service:OrganizationProfileService|undefined,origin:string|undefined){const m=route.exec(new URL(r.url??"/","http://invalid").pathname);if(!m)return false;const send=(x:ProfileWriteResult)=>{s.writeHead(x.status,{"content-type":"application/json","cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer"});s.end(JSON.stringify(x.body))};try{if(!service||!origin){send({status:503,body:{error:"unavailable"}});return true}const session=cookie(r.headers.cookie),org=decodeURIComponent(m[1]!);if(m[3]){if(r.method!=="GET"){send({status:404,body:{error:"not_found"}});return true}send(await service.receipt(session,org,m[3]));return true}if(r.method!=="POST"){send({status:404,body:{error:"not_found"}});return true}if(r.headers.origin!==origin||r.headers["sec-fetch-site"]==="cross-site"){r.resume();send({status:403,body:{error:"origin_rejected"}});return true}if(r.headers["content-type"]!=="application/json"){r.resume();send({status:400,body:{error:"invalid_request"}});return true}const body=await json(r);if(!body.ok){send({status:400,body:{error:"invalid_request"}});return true}send(await(m[2]==="preview"?service.preview(session,org,body.value):service.confirm(session,org,body.value)))}catch{if(!s.headersSent)send({status:503,body:{error:"unavailable"}});else s.destroy()}return true}
