import {createHash} from "node:crypto";
import pg from "pg";
import type {CommitInput,CommitOutcome,Receipt,SafeWriteStore} from "@studenthub/safe-write-contract";
import {principalAuditRef} from "./authorization-audit.js";
import {databaseUrl} from "./connection.js";
const OP="profile.safe_write", hex=/^[0-9a-f]{64}$/;
const ORGANIZATION_PROFILE_FIELDS=["name_ar","name_en","description_ar","description_en","website"] as const;
const organizationProfileRef=(id:string)=>createHash("sha256").update(`studenthub:organization-profile-ref:v1\0${id}`).digest("hex");
const organizationProfilePrincipalRef=principalAuditRef;
const tokenRef=(id:string)=>createHash("sha256").update(`studenthub:safe-write-token-ref:v1\0${id}`).digest("hex");
class Refusal extends Error {constructor(readonly reason:"state_changed"|"token_already_used"|"not_own_record"){super(reason)}}
export class PostgresOrganizationProfileStore {
 readonly #pool:pg.Pool;readonly #owns:boolean;
 constructor(options:{connectionString?:string;pool?:pg.Pool}={}){this.#owns=!options.pool;this.#pool=options.pool??new pg.Pool({connectionString:options.connectionString??databaseUrl()});}
 async close(){if(this.#owns)await this.#pool.end();}
 forOwner(principalId:string,orgId:string):SafeWriteStore {const principalRef=organizationProfilePrincipalRef(principalId),recordRef=organizationProfileRef(orgId);return {
  ownedRecord:async p=>p===principalRef&&await this.#ownsOrg(this.#pool,principalId,orgId)?recordRef:null,
  readField:async(r,f)=>r===recordRef&&ORGANIZATION_PROFILE_FIELDS.includes(f as never)?this.#read(this.#pool,orgId,f):null,
  commit:async i=>i.principalRef===principalRef&&i.personRef===recordRef?this.#commit(principalId,orgId,i):({ok:false,reason:"not_own_record"})};}
 async readReceipt(principalId:string,orgId:string,receiptRef:string):Promise<Receipt|null>{if(!hex.test(receiptRef))return null;const {rows}=await this.#pool.query<{request_ref:string;actor_principal_ref:string;after_summary:Record<string,unknown>}>(`SELECT request_ref,actor_principal_ref,after_summary FROM authorization_mutation_audit WHERE operation=$1 AND request_ref=$2 AND actor_principal_ref=$3 AND target_org_refs=ARRAY[$4]`,[OP,receiptRef,organizationProfilePrincipalRef(principalId),orgId]);const r=rows[0],a=r?.after_summary;if(!r||!a||a.personRef!==organizationProfileRef(orgId)||!Array.isArray(a.fields)||a.fields.length!==1||!ORGANIZATION_PROFILE_FIELDS.includes(a.fields[0] as never)||typeof a.contractVersion!=="string"||typeof a.changeSetDigest!=="string"||!hex.test(a.changeSetDigest)||typeof a.committedAt!=="string")return null;return Object.freeze({contractVersion:a.contractVersion,receiptRef:r.request_ref,personRef:a.personRef,principalRef:r.actor_principal_ref,changeSetDigest:a.changeSetDigest,fields:Object.freeze([a.fields[0]]),committedAt:a.committedAt}) as Receipt;}
 async #ownsOrg(c:pg.Pool|pg.PoolClient,p:string,o:string){return (await c.query("SELECT 1 FROM grants WHERE principal_id=$1 AND org_id=$2 AND role='org-owner'",[p,o])).rows.length===1;}
 async #read(c:pg.Pool|pg.PoolClient,o:string,f:string){return (await c.query<{value:string}>("SELECT value FROM organization_profile_fields WHERE org_id=$1 AND field=$2",[o,f])).rows[0]?.value??null;}
 async #commit(p:string,o:string,input:CommitInput):Promise<CommitOutcome>{if(!ORGANIZATION_PROFILE_FIELDS.includes(input.field as never)||input.receipt.fields.length!==1||input.receipt.fields[0]!==input.field)throw new TypeError("inconsistent organization profile write");const c=await this.#pool.connect();try{await c.query("BEGIN");await c.query("SELECT pg_advisory_xact_lock(hashtextextended($1,5959))",[p]);if(!await this.#ownsOrg(c,p,o))throw new Refusal("not_own_record");if((await c.query("SELECT 1 FROM authorization_mutation_audit WHERE operation=$1 AND after_summary->>'tokenRef'=$2",[OP,tokenRef(input.tokenId)])).rows.length)throw new Refusal("token_already_used");if((await this.#read(c,o,input.field))!==input.expectedBefore)throw new Refusal("state_changed");await c.query(`INSERT INTO organization_profile_fields(org_id,field,value) VALUES($1,$2,$3) ON CONFLICT(org_id,field) DO UPDATE SET value=EXCLUDED.value,updated_at=clock_timestamp()`,[o,input.field,input.value]);await c.query(`INSERT INTO authorization_mutation_audit(request_ref,actor_principal_ref,operation,target_principal_ref,target_org_refs,before_summary,after_summary) VALUES($1,$2,$3,$2,ARRAY[$4],$5::jsonb,$6::jsonb)`,[input.receipt.receiptRef,input.receipt.principalRef,OP,o,JSON.stringify({valuePresent:input.expectedBefore!==null}),JSON.stringify({contractVersion:input.receipt.contractVersion,personRef:input.receipt.personRef,changeSetDigest:input.receipt.changeSetDigest,fields:[input.field],committedAt:input.receipt.committedAt,tokenRef:tokenRef(input.tokenId)})]);await c.query("COMMIT");return {ok:true};}catch(e){await c.query("ROLLBACK").catch(()=>{});if(e instanceof Refusal)return {ok:false,reason:e.reason};if((e as {code?:string}).code==="23505")return {ok:false,reason:"token_already_used"};throw e;}finally{c.release();}}
}
