import assert from "node:assert/strict";import {test} from "node:test";import {createHash} from "node:crypto";
import {runSafeWriteConformance,type CommitInput,type Receipt,type SafeWriteStore} from "@studenthub/safe-write-contract";
const modulePromise=import(process.env.SHU160_TEST_MODULE??"../src/profile-writes.js");
const documentModulePromise=import(process.env.SHU160_DOC_MODULE??"../../private-documents/src/organization-documents.js");
const ref=(d:string,v:string)=>createHash("sha256").update(`studenthub:${d}:v1\0${v}`).digest("hex"),profileRef=(v:string)=>ref("organization-profile-ref",v),principalRef=(v:string)=>ref("principal-audit-ref",v);
class Memory{fields=new Map<string,string>();receipts=new Map<string,Receipt>();roles=new Map<string,string>();commits:CommitInput[]=[];forOwner(p:string,o:string):SafeWriteStore{const rr=profileRef(o),pr=principalRef(p);return{ownedRecord:()=>this.roles.get(`${p}:${o}`)==="org-owner"?rr:null,readField:(r,f)=>r===rr?this.fields.get(`${o}:${f}`)??null:null,commit:i=>{if(i.personRef!==rr||i.principalRef!==pr||this.roles.get(`${p}:${o}`)!=="org-owner")return{ok:false,reason:"not_own_record"};const k=`${o}:${i.field}`;if((this.fields.get(k)??null)!==i.expectedBefore)return{ok:false,reason:"state_changed"};this.fields.set(k,i.value);this.receipts.set(`${p}:${o}:${i.receipt.receiptRef}`,i.receipt);this.commits.push(i);return{ok:true}}};}async readReceipt(p:string,o:string,r:string){return this.receipts.get(`${p}:${o}:${r}`)??null;}}
const fixture=async()=>{const{createOrganizationProfileWrites}=await modulePromise;const store=new Memory();store.roles.set("owner:acme","org-owner");store.roles.set("owner:other","org-owner");store.roles.set("recruiter:acme","recruiter");return{store,service:createOrganizationProfileWrites({store,secret:"synthetic-safe-write-secret-at-least-32-bytes"})}};
test("SHU-160/AC-01 SAFE-WRITE website passes conformance and cannot bypass preview",async()=>{const{buildOrganizationProfileSafeWrite}=await modulePromise;const report=await runSafeWriteConformance(buildOrganizationProfileSafeWrite);assert.equal(report.ok,true,report.results.filter(x=>!x.ok).map(x=>x.detail).join());const{store,service}=await fixture();const b={field:"website",value:"https://acme.example"};const p=await service.preview("owner","acme",b);assert.equal(p.status,200);assert.equal(store.commits.length,0);assert.equal((await service.confirm("owner","acme",{...b,token:(p.body as any).token})).status,200);assert.equal(store.commits.length,1)});
test("SHU-160/AC-03 recruiter-write-refused",async()=>{const{service}=await fixture();assert.deepEqual(await service.preview("recruiter","acme",{field:"name_en",value:"Acme"}),{status:404,body:{error:"not_found"}})});
test("SHU-160/AC-02 private-delivery negative-control",async()=>{const{organizationDocumentInput}=await documentModulePromise;const input=organizationDocumentInput("acme","commercial-licence","application/pdf",Buffer.from("synthetic"));assert.equal(input.acl,"private");assert.equal("url" in input,false);assert.equal("key" in input,false)});
test("SHU-160/AC-04 receipt-whitelist",async()=>{const{service}=await fixture(),b={field:"description_en",value:"Synthetic company"};const p=await service.preview("owner","acme",b),c=await service.confirm("owner","acme",{...b,token:(p.body as any).token}),r=(c.body as any).receipt;assert.deepEqual(Object.keys(r).sort(),["changeSetDigest","committedAt","contractVersion","fields","personRef","principalRef","receiptRef"]);assert.equal(/url|key/.test(JSON.stringify(r)),false)});
test("SHU-160/AC-05 cross-org",async()=>{const{service}=await fixture(),b={field:"name_ar",value:"شركة"},p=await service.preview("owner","acme",b);assert.notEqual((await service.confirm("owner","other",{...b,token:(p.body as any).token})).status,200)});
