export const probes = [
  ['completes only', '', 'Completes only SHU-253', false],
  ['closes only', '', 'Closes only SHU-253', false],
  ['title reference', 'Implement acceptance (SHU-253)', '', false],
  ['title completion', 'Completes only SHU-253', '', false],
  ['punctuation', '', 'Closes: (SHU-253).', false],
  ['line break', '', 'Completes only\n\nSHU-253', false],
  ['split reference', '', 'Closes SHU-\n253', false],
  ['case', '', 'rEsOlVeS shu-253', false],
  ['past tense', '', 'This has completed the work for SHU-253.', false],
  ['future tense', '', 'This will finish the acceptance work for SHU-253.', false],
  ['neutral reference', '', 'Related: SHU-253', false],
  ['negation', '', 'Does not close SHU-253', false],
  ['quoted example', '', '`Fixes SHU-253`', false],
  ['url', '', 'Related: https://linear.app/team/issue/SHU-253/acceptance', false],
  ['url without id', '', 'https://linear.app/team/issue/opaque', false],
  ['unicode dash', '', 'Completes SHU–253', false],
  ['unicode width', '', 'Closes ＳＨＵ－２５３', false],
  ['zero width', '', 'Closes SHU-\u200B253', false],
  ['other team', '', 'Closes ACCEPT-42', false],
  ['neutral repository link', '', 'Related work: [acceptance record](docs/acceptance-record.md)', true],
  ['completes without issue', '', 'Completes only the local parser tests.', true],
  ['closes without issue', '', 'Closes only the local file descriptor.', true],
  ['neutral title', 'Add repository acceptance policy', '', true],
  ['punctuation without issue', '', 'Fixes: parsing.\nResolves local test failures.', true],
  ['issue prose without identifier', '', 'Live acceptance remains pending owner proof.', true],
];
