import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, before, test } from "node:test";
import pg from "pg";
import { createOrganization, createPrincipal } from "@studenthub/contracts";
import { buildOrganizationProfileWrite, organizationOwnerDecision, organizationProfilePrincipalRef,
  organizationProfileRecordRef, organizationProfileStateDecision } from "@studenthub/organizations";
import { ORGANIZATION_PROFILE_OPERATION, organizationAuditRef, PostgresAuthzStore,
  PostgresOrganizationProfileStore, runMigrations } from "@studenthub/db";

const URL=process.env.DATABASE_URL??"", KEY="shu300-postgres-test-secret-at-least-thirty-two-bytes", ORG=`shu300-${randomUUID()}`, OTHER=`shu300-${randomUUID()}`;
let pool:pg.Pool,authz:PostgresAuthzStore,store:PostgresOrganizationProfileStore;
before(async()=>{if(!URL)throw new Error("DATABASE_URL is required to run the db suite");pool=new pg.Pool({connectionString:URL});await runMigrations(pool);authz=new PostgresAuthzStore(pool);await authz.upsertOrganization(createOrganization({id:ORG,name:"SHU-300 synthetic"}));await authz.upsertOrganization(createOrganization({id:OTHER,name:"SHU-300 other"}));store=new PostgresOrganizationProfileStore({pool,ownerDecision:organizationOwnerDecision,stateDecision:organizationProfileStateDecision,recordRef:organizationProfileRecordRef,principalRef:organizationProfilePrincipalRef});});
after(async()=>{await pool.end();});
async function owner(){const id=`shu300-${randomUUID()}`;await authz.registerPrincipal(createPrincipal({id,pbuuids:[],email:`${id}@example.invalid`}));await authz.grantMany(id,[{orgId:ORG,role:"org-owner"}]);return id;}
test("SHU-300 postgres successful commit stores profile and hashed organization audit reference",async()=>{const id=await owner();const writer=buildOrganizationProfileWrite({store:store.forPrincipal(id,ORG),secret:KEY});const change={personRef:organizationProfileRecordRef(ORG),field:"name_en",value:"Synthetic Company"};const p=await writer.preview({principalRef:organizationProfilePrincipalRef(id),change});assert.ok(p.ok);const done=await writer.confirm({principalRef:organizationProfilePrincipalRef(id),change,token:p.token});assert.ok(done.ok);const profile=await pool.query("SELECT name_en FROM organization_profiles WHERE org_id=$1",[ORG]);assert.equal(profile.rows[0].name_en,"Synthetic Company");const audit=await pool.query("SELECT operation,target_org_refs FROM authorization_mutation_audit WHERE request_ref=$1",[done.receipt.receiptRef]);assert.deepEqual(audit.rows,[{operation:ORGANIZATION_PROFILE_OPERATION,target_org_refs:[organizationAuditRef(ORG)]}]);});
test("SHU-300 postgres duplicate racing confirms return token_already_used",async()=>{const id=await owner();const a=buildOrganizationProfileWrite({store:store.forPrincipal(id,ORG),secret:KEY}),b=buildOrganizationProfileWrite({store:store.forPrincipal(id,ORG),secret:KEY});const change={personRef:organizationProfileRecordRef(ORG),field:"website",value:"https://race.invalid"};
  // Store the value first, so the raced change is a no-op. Otherwise the contract's own pre-read can
  // refuse the losing confirm as state_changed before it reaches the store's single-use check.
  const first=await a.preview({principalRef:organizationProfilePrincipalRef(id),change});assert.ok(first.ok);assert.ok((await a.confirm({principalRef:organizationProfilePrincipalRef(id),change,token:first.token})).ok);
  const p=await a.preview({principalRef:organizationProfilePrincipalRef(id),change});assert.ok(p.ok);const results=await Promise.all([a,b].map(x=>x.confirm({principalRef:organizationProfilePrincipalRef(id),change,token:p.token})));assert.equal(results.filter(x=>x.ok).length,1);assert.equal(results.filter(x=>!x.ok&&x.reason==="token_already_used").length,1);});
test("SHU-300 postgres store refuses recruiter and cross-organization owner grants",async()=>{const recruiter=`shu300-${randomUUID()}`,cross=`shu300-${randomUUID()}`;for(const id of [recruiter,cross])await authz.registerPrincipal(createPrincipal({id,pbuuids:[],email:`${id}@example.invalid`}));await authz.grantMany(recruiter,[{orgId:ORG,role:"recruiter"}]);await authz.grantMany(cross,[{orgId:OTHER,role:"org-owner"}]);for(const id of [recruiter,cross]){const writer=buildOrganizationProfileWrite({store:store.forPrincipal(id,ORG),secret:KEY});const result=await writer.preview({principalRef:organizationProfilePrincipalRef(id),change:{personRef:organizationProfileRecordRef(ORG),field:"name_en",value:"Forbidden"}});assert.deepEqual(result,{ok:false,reason:"not_own_record"});}});
test("SHU-300 postgres store detects a value changed after preview",async()=>{const id=await owner();const writer=buildOrganizationProfileWrite({store:store.forPrincipal(id,ORG),secret:KEY});const change={personRef:organizationProfileRecordRef(ORG),field:"description_en",value:"Previewed"};const preview=await writer.preview({principalRef:organizationProfilePrincipalRef(id),change});assert.ok(preview.ok);await pool.query("INSERT INTO organization_profiles (org_id,description_en) VALUES ($1,$2) ON CONFLICT (org_id) DO UPDATE SET description_en=EXCLUDED.description_en",[ORG,"Concurrent"]);const result=await writer.confirm({principalRef:organizationProfilePrincipalRef(id),change,token:preview.token});assert.deepEqual(result,{ok:false,reason:"state_changed"});});
